site_name: Podcast 内容

docs_dir: docs
plugins:
  - awesome-pages
  - search

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

